"""Route pricing configuration — x402 payment routes and their costs."""
from x402.http.types import RouteConfig
from x402.http import PaymentOption


def build_routes(wallet_address: str, network: str) -> dict[str, RouteConfig]:
    """Build the x402 route pricing table."""
    def _rc(price: str, description: str) -> RouteConfig:
        return RouteConfig(
            accepts=[PaymentOption(scheme="exact", pay_to=wallet_address, price=price, network=network)],
            mime_type="application/json",
            description=description,
        )

    return {
        # ── AI Tools ─────────────────────────────────────────────────────────
        "POST /scrape":       _rc("$0.01", "Fetch any URL and return clean markdown text ($0.01)"),
        "POST /search":       _rc("$0.01", "DuckDuckGo web search, returns top N results ($0.01)"),
        "POST /research":     _rc("$0.05", "Deep research: search + scrape + Claude synthesis with citations ($0.05)"),
        "POST /write":        _rc("$0.02", "Claude writes content (article, post, copy) to your spec ($0.02)"),
        "POST /analyze":      _rc("$0.01", "Claude analyzes data or text and returns structured insights ($0.01)"),
        "POST /code":         _rc("$0.02", "Claude generates code from a description in any language ($0.02)"),
        "POST /summarize":    _rc("$0.01", "Claude summarizes long text or articles into key points ($0.01)"),
        "POST /translate":    _rc("$0.01", "Claude translates text to any language ($0.01)"),
        "POST /social":       _rc("$0.02", "Claude generates platform-optimized social media posts ($0.02)"),
        "POST /batch":        _rc("$0.03", "Run up to 5 AI operations in one payment — research, write, analyze, translate, social, code ($0.03)"),
        "POST /extract":      _rc("$0.01", "Extract structured data from any text using a schema you define ($0.01)"),
        "POST /qa":           _rc("$0.01", "Answer a question given a context document — core RAG building block ($0.01)"),
        "POST /classify":     _rc("$0.01", "Classify text into your defined categories with confidence scores ($0.01)"),
        "POST /sentiment":    _rc("$0.01", "Deep sentiment analysis — polarity, emotions, confidence, key phrases ($0.01)"),
        "POST /keywords":     _rc("$0.01", "Extract keywords, topics, tags, and entities from any text ($0.01)"),
        "POST /compare":      _rc("$0.01", "Compare two texts — similarities, differences, recommendation ($0.01)"),
        "POST /transform":    _rc("$0.01", "Transform text with any instruction — rewrite, reformat, clean, expand, condense ($0.01)"),
        "POST /chat":         _rc("$0.02", "Stateless multi-turn chat — send message history, get Claude's reply ($0.02)"),
        "POST /plan":         _rc("$0.02", "Generate a step-by-step action plan for any goal ($0.02)"),
        "POST /decide":       _rc("$0.02", "Decision framework — pros/cons, risks, and a recommendation ($0.02)"),
        "POST /proofread":    _rc("$0.01", "Grammar, spelling, clarity corrections with tracked changes ($0.01)"),
        "POST /explain":      _rc("$0.01", "Explain any concept at beginner, intermediate, or expert level ($0.01)"),
        "POST /questions":    _rc("$0.01", "Generate interview, FAQ, or quiz questions from any content ($0.01)"),
        "POST /outline":      _rc("$0.01", "Generate a structured hierarchical outline from a topic or document ($0.01)"),
        "POST /email":        _rc("$0.02", "Compose professional emails — subject, body, tone, length ($0.02)"),
        "POST /sql":          _rc("$0.02", "Natural language to SQL — describe what you want, get a query ($0.02)"),
        "POST /regex":        _rc("$0.01", "Generate regex patterns from plain English description ($0.01)"),
        "POST /mock":         _rc("$0.02", "Generate realistic mock data — JSON, CSV, or plain list ($0.02)"),
        "POST /score":        _rc("$0.01", "Score content quality on any custom rubric — returns per-criterion scores ($0.01)"),
        "POST /timeline":     _rc("$0.01", "Extract or generate a chronological timeline of events from text ($0.01)"),
        "POST /action":       _rc("$0.01", "Extract action items, tasks, and owners from meeting notes or text ($0.01)"),
        "POST /pitch":        _rc("$0.02", "Generate elevator pitch — hook, value prop, call to action ($0.02)"),
        "POST /debate":       _rc("$0.02", "Arguments for and against any position with strength ratings ($0.02)"),
        "POST /headline":     _rc("$0.01", "Generate compelling headlines and titles for any content ($0.01)"),
        "POST /fact":         _rc("$0.01", "Extract factual claims from text with source hints and verifiability scores ($0.01)"),
        "POST /rewrite":      _rc("$0.01", "Rewrite text for a specific audience, reading level, or brand voice ($0.01)"),
        "POST /tag":          _rc("$0.01", "Auto-tag content using a provided taxonomy or free-form tagging ($0.01)"),
        "POST /pipeline":     _rc("$0.05", "Chain up to 5 operations where each step can use the previous output ($0.05)"),

        # ── API & Scraping ───────────────────────────────────────────────────
        "POST /api-call":            _rc("$0.05", "Proxy HTTP call to any cataloged API with optional Claude enrichment ($0.03)"),
        "POST /scrape/google-maps":  _rc("$0.05", "Scrape Google Maps places for any query — names, addresses, ratings ($0.05)"),
        "POST /scrape/instagram":    _rc("$0.03", "Scrape Instagram profile posts and metadata ($0.03)"),
        "POST /scrape/tweets":       _rc("$0.03", "Scrape tweets by search query or hashtag ($0.03)"),
        "POST /scrape/linkedin":     _rc("$0.05", "Scrape LinkedIn profile data ($0.05)"),
        "POST /scrape/youtube":      _rc("$0.03", "Scrape YouTube video metadata by search keyword ($0.03)"),
        "POST /scrape/web":          _rc("$0.03", "Crawl any website and extract structured content ($0.03)"),
        "POST /scrape/tiktok":       _rc("$0.03", "Scrape TikTok profile videos and metadata ($0.03)"),
        "POST /scrape/facebook-ads": _rc("$0.05", "Scrape Facebook Ad Library for any brand or keyword ($0.05)"),
        "POST /scrape/actor":        _rc("$0.03", "Run any Apify actor by ID with custom input ($0.03)"),

        # ── Vision & Advanced AI ─────────────────────────────────────────────
        "POST /vision":       _rc("$0.02", "Analyze any image URL with Claude Vision — describe, extract, or answer questions ($0.02)"),
        "POST /rag":          _rc("$0.02", "Mini RAG — provide documents + query, get a grounded answer with citations ($0.02)"),
        "POST /diagram":      _rc("$0.02", "Generate Mermaid diagrams (flowchart, sequence, erd, gantt, mindmap) from description ($0.02)"),
        "POST /json-schema":  _rc("$0.01", "Generate JSON Schema (draft-07) from a plain English description ($0.01)"),
        "POST /test-cases":   _rc("$0.02", "Generate comprehensive test cases for code or a feature description ($0.02)"),
        "POST /workflow":     _rc("$0.10", "Multi-step agentic reasoning — Claude Sonnet breaks down and executes complex goals ($0.10)"),

        # ── Code Tools ───────────────────────────────────────────────────────
        "POST /review-code":       _rc("$0.05", "Code review — quality, security, and performance analysis with actionable fixes ($0.05)"),
        "POST /generate-docs":     _rc("$0.03", "Generate documentation for code — jsdoc, docstring, rustdoc ($0.03)"),
        "POST /convert-code":      _rc("$0.03", "Convert code between programming languages ($0.03)"),
        "POST /generate-api-spec": _rc("$0.05", "Generate OpenAPI spec from natural language description ($0.05)"),
        "POST /diff":              _rc("$0.02", "Analyze differences between two texts or code snippets ($0.02)"),
        "POST /parse-csv":         _rc("$0.03", "Analyze CSV data and answer questions about it ($0.03)"),
        "POST /cron":              _rc("$0.01", "Generate or explain cron expressions from natural language ($0.01)"),
        "POST /changelog":         _rc("$0.02", "Generate changelog from commit messages ($0.02)"),
        "POST /name-generator":    _rc("$0.02", "Generate product/company/feature names with taglines ($0.02)"),
        "POST /privacy-check":     _rc("$0.02", "Scan text for PII, secrets, and sensitive data ($0.02)"),
        "POST /think":             _rc("$0.10", "Autonomous chain-of-thought reasoning — breaks down problems, calls tools, returns structured solution ($0.10)"),

        # ── Agent Memory ─────────────────────────────────────────────────────
        "POST /memory/set":    _rc("$0.01", "Store a persistent memory value for an agent — survives across sessions ($0.01)"),
        "POST /memory/get":    _rc("$0.01", "Retrieve a stored memory by agent_id and key ($0.01)"),
        "POST /memory/search": _rc("$0.01", "Search all memories for an agent by keyword — returns ranked matches ($0.01)"),
        "POST /memory/list":   _rc("$0.01", "List all memory keys for an agent ($0.01)"),
        "POST /memory/clear":  _rc("$0.01", "Delete all memories for an agent_id ($0.01)"),

        # ── Agent Network ────────────────────────────────────────────────────
        "POST /chain":             _rc("$0.05", "Chain up to 5 AI endpoints in sequence — each step can reference prior results ($0.05)"),
        "POST /marketplace/call":  _rc("$0.03", "Proxy-call any agent marketplace listing — we handle routing and payment"),
        "POST /message/send":      _rc("$0.01", "Send a direct message from one agent to another ($0.01)"),
        "POST /message/broadcast": _rc("$0.01", "Broadcast a message to all agents in the network ($0.01)"),
        "POST /message/reply":     _rc("$0.01", "Reply to a message, preserving the thread ($0.01)"),
        "POST /knowledge/add":     _rc("$0.01", "Add an entry to the shared agent knowledge base ($0.01)"),
        "POST /task/submit":       _rc("$0.01", "Post a task to the agent task board ($0.01)"),
        "POST /task/complete":     _rc("$0.01", "Mark a claimed task as complete and submit the result ($0.01)"),

        # ── Execution & Infra ────────────────────────────────────────────────
        "POST /code/run":      _rc("$0.02", "Execute Python code in a sandboxed subprocess, returns stdout/stderr ($0.02)"),
        "GET /web/search":     _rc("$0.02", "DuckDuckGo web search — instant answers + related results ($0.02)"),
        "POST /enrich":        _rc("$0.02", "Entity enrichment — aggregate data about an IP, crypto, country, or company ($0.02)"),
        "POST /credits/buy":   _rc("$5.00", "Buy $5 credit pack — returns prepaid API key for metered token-based billing"),
        "POST /session/start": _rc("$0.001", "Start persistent agent session with shared context"),
        "POST /workflow/run":  _rc("$0.02", "Run multi-step AI workflow — chain tools together with 15% discount"),

        # ── Utility Tools (API Toll-style) ──────────────────────────────────
        "GET /data/geocode":          _rc("$0.001", "Address to coordinates (geocode)"),
        "GET /data/geocode/reverse":  _rc("$0.001", "Coordinates to address (reverse geocode)"),
        "GET /data/company":          _rc("$0.005", "Company/corporate entity search"),
        "GET /data/whois":            _rc("$0.002", "Domain WHOIS/RDAP lookup"),
        "GET /data/domain":           _rc("$0.003", "Full domain profile (DNS + WHOIS)"),
        "POST /data/readability":     _rc("$0.001", "Readability score (Flesch-Kincaid)"),
        "GET /data/language":         _rc("$0.001", "Language detection"),
        "POST /data/profanity":       _rc("$0.001", "Profanity filter/detection"),
        "GET /data/meta":             _rc("$0.002", "URL meta tags (OG, Twitter Cards)"),
        "GET /data/links":            _rc("$0.002", "Extract all links from URL"),
        "GET /data/sitemap":          _rc("$0.002", "Parse sitemap.xml"),
        "GET /data/robots":           _rc("$0.001", "Parse robots.txt"),
        "GET /data/headers":          _rc("$0.001", "HTTP response headers"),
        "GET /data/ssl":              _rc("$0.002", "SSL certificate info"),
        "POST /data/jwt/decode":      _rc("$0.001", "JWT token decode"),
        "POST /data/markdown":        _rc("$0.002", "Markdown to HTML"),
        "GET /data/placeholder":      _rc("$0.001", "Placeholder image (SVG)"),
        "GET /data/favicon":          _rc("$0.001", "Favicon extraction"),
        "GET /data/avatar":           _rc("$0.001", "Deterministic identicon avatar"),
        "GET /data/ens":              _rc("$0.002", "ENS name/address resolution"),
        "GET /data/enrich/domain":    _rc("$0.020", "Domain enrichment (tech stack, socials, DNS)"),
        "GET /data/enrich/github":    _rc("$0.010", "GitHub user profile + top repos"),
        "POST /data/email/send":      _rc("$0.003", "Send email via Resend"),
        "POST /data/extract/text":    _rc("$0.002", "HTML to clean text"),
        "POST /data/extract/pdf":     _rc("$0.010", "PDF to text extraction"),
        "GET /data/finance/history":  _rc("$0.005", "Historical OHLCV stock candles"),
        "GET /data/finance/forex":    _rc("$0.001", "150+ currency exchange rates"),
        "GET /data/finance/convert":  _rc("$0.001", "Currency conversion"),
        "POST /data/entities":        _rc("$0.002", "Named entity extraction"),
        "POST /data/similarity":      _rc("$0.002", "Text similarity scoring"),
        "POST /data/transform/json-to-csv": _rc("$0.002", "JSON to CSV conversion"),
        "POST /data/transform/xml":   _rc("$0.002", "XML to JSON conversion"),
        "POST /data/transform/yaml":  _rc("$0.002", "YAML to JSON conversion"),
        "GET /data/datetime/between": _rc("$0.001", "Duration between dates"),
        "GET /data/datetime/business-days": _rc("$0.001", "Business days calculator"),
        "GET /data/datetime/unix":    _rc("$0.001", "Unix timestamp converter"),
        "GET /data/security/headers": _rc("$0.003", "Security headers audit (A+ to F)"),
        "GET /data/security/techstack": _rc("$0.005", "Technology stack detection"),
        "GET /data/security/uptime":  _rc("$0.001", "URL uptime check"),
        "POST /data/math/eval":       _rc("$0.001", "Math expression evaluator"),
        "GET /data/math/convert":     _rc("$0.001", "Unit converter"),
        "POST /data/math/stats":      _rc("$0.002", "Statistical analysis"),
        "GET /data/crypto/trending":  _rc("$0.001", "Trending crypto tokens"),
    }
